print("Please Enter Score Foundation English")
FoundationEnglish = float(input())
print("Please Enter Score General Business")
GeneralBusiness = float(input())
print("Please Enter Score Introduction to Computer Systems")
IntroductionComputerSystems = float(input())
print("Please Enter Score Introduction to Computer Programming")
ComputerProgramming = float(input())

print("--- Your Score ---")
print("Foundation English : ",FoundationEnglish," Score")
print("General Business   : ",GeneralBusiness,"   Score")
print("Introduction to Computer Systems : ",IntroductionComputerSystems," Score")
print("Computer Programming : ",ComputerProgramming," Score")
